services:
  db:
    image: postgres:17
    container_name: db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - 5432:5432
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro